name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: digreat007/buildozer-action@v2
        with:
          python-version: '3.10'
          buildozer-cmd: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ElimuYetApp-APK
          path: bin/*.apk
